### ISSUE TITLE
240页bitmap实现疑问

### ISSUE THREAD

**Issue by lianxiaolei** [bjweimengshu/ProgrammerXiaohui#10]
第32行，应该是(1L << bitIndex) mod 64;吧。

**Comment by Tamtian** [comment]
我也觉得，或者该写为(1L << (bitIndex % 64)); ？

**Comment by bjweimengshu** [comment]
这里没有问题，<<操作符的移动是循环的，比如把数字1左移64位，最终结果仍然是1。
