### ISSUE TITLE
《漫画算法》勘误表

### ISSUE THREAD

**Issue by bjweimengshu** [bjweimengshu/ProgrammerXiaohui#5]
小灰的漫画算法，整理了一个勘误表，欢迎大家指正：http://mp.weixin.qq.com/s?__biz=MzIxMjE5MTE1Nw==&mid=505714242&idx=1&sn=59526f45b94db2f4be750273431e8867&chksm=0c99e4983bee6d8eb4beed7f6143bbbc00659f32056b37db1d3f1b925ca6867d7d2c34d6ad64#rd

**Comment by wanbing0610** [comment]
这么多买书的,缺没有几个提交的！~我来。。。。

**Comment by ZeroYale** [comment]
数组那里的代码看了几遍，觉得有问题，找小灰公众号要源码，才知道是书出现错误了。。。

**Comment by PeppaLittlePig** [comment]
有点尴尬 第一次买书发现这么多错误的 ..

**Comment by JKAK47** [comment]
PriorityQueue.java 这个优先级队列实现，你插入元素按照最小堆实现，删除元素怎么按照最大堆实现呢？
