### ISSUE TITLE
chapter3/part2/BinaryTreeTraversal.java

### ISSUE THREAD

**Issue by wanbing0610** [bjweimengshu/ProgrammerXiaohui#8]
public static TreeNode createBinaryTree(LinkedList<Integer> inputList){
        TreeNode node = null;
        if(inputList==null || inputList.isEmpty()){
            return null;
        }
        Integer data = inputList.removeFirst();     //这里会remove  inputList
        if(data != null){
            node = new TreeNode(data);
            node.leftChild = createBinaryTree(inputList); //这里会把所有的inputList递归remove完
            node.rightChild = createBinaryTree(inputList);//等到执行到这里时,inputList是为空
        }
        return node;
    }
   //最终变成只有左节点的树

**Comment by bjweimengshu** [comment]
又看了下，这段代码没毛病，当构造数组出现null的时候，代表某个节点没有左孩子或右孩子，这时候不会继续往下递归了。比如main函数中给出的数组：{3,2,9,null,null,10,null,null,8,null,4,}。
所以，并不会出现只有左孩子的树。
